; Script generated by the Inno Setup Script Wizard.
#define MyAppName "ComputeKart"
#define MyAppVersion "0.1.8"
#define MyAppExeName "compute_kart.exe"
#define ProjectRoot "D:\dixith\desktop_computekart"

[Setup]
AppId={{16CEA89B-A740-4EA8-9B95-52081A792F59}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
DefaultDirName={autopf}\{#MyAppName}
PrivilegesRequired=admin
ChangesEnvironment=yes
OutputDir={#ProjectRoot}\installers
OutputBaseFilename=computekart
SolidCompression=yes

[Files]
Source: "{#ProjectRoot}\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ProjectRoot}\Indra-cli\*"; DestDir: "{app}\Indra-cli"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; \
    ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}\Indra-cli"; \
    Check: NeedsAddPath(ExpandConstant('{app}\Indra-cli'))

[Code]
var
  WslCheckBox, WinCliCheckBox: TNewCheckBox;

function NeedsAddPath(Param: string): boolean;
var OrigPath: string;
begin
  if not RegQueryStringValue(HKLM, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'Path', OrigPath) then Result := True 
  else Result := Pos(';' + UpperCase(Param) + ';', ';' + UpperCase(OrigPath) + ';') = 0;
end;

procedure InitializeWizard;
var WslCustomPage: TWizardPage;
begin
  WslCustomPage := CreateCustomPage(wpReady, 'Installation Options', 'Select components to install.');
  WslCheckBox := TNewCheckBox.Create(WslCustomPage);
  WslCheckBox.Parent := WslCustomPage.Surface;
  WslCheckBox.Caption := 'Install/Configure WSL & Ubuntu';
  WslCheckBox.Checked := True;
  WinCliCheckBox := TNewCheckBox.Create(WslCustomPage);
  WinCliCheckBox.Parent := WslCustomPage.Surface;
  WinCliCheckBox.Top := 30;
  WinCliCheckBox.Caption := 'Install Windows CLI';
  WinCliCheckBox.Checked := True;
end;

procedure RunCkartInsideWsl();
var
  Res: Integer;
  WslPath, BashCmd, UserTarget: String;
begin
  UserTarget := 'harshith';
  WslPath := '/mnt/c/Progra~1/ComputeKart/Indra-cli';

  // 1. Run the existing install script as the user
  Exec('wsl.exe', '-u ' + UserTarget + ' bash ' + WslPath + '/Install-ckart.sh', '', SW_SHOW, ewWaitUntilTerminated, Res);
  
  // 2. Ensure the ckart file is executable for the user
  Exec('wsl.exe', '-u ' + UserTarget + ' chmod +x ' + WslPath + '/ckart', '', SW_HIDE, ewWaitUntilTerminated, Res);
  
  // 3. Add to user's .bashrc ONLY if not already present
  BashCmd := 'bash -c "grep -q ''export PATH=.*Indra-cli'' /home/' + UserTarget + '/.bashrc || echo ''export PATH=$PATH:' + WslPath + ''' >> /home/' + UserTarget + '/.bashrc"';
  Exec('wsl.exe', '-u ' + UserTarget + ' ' + BashCmd, '', SW_HIDE, ewWaitUntilTerminated, Res);
end;

procedure CurStepChanged(CurStep: TSetupStep);
var 
  Res: Integer;
  BatContent: String;
  AppPath: String;
begin
  if CurStep = ssPostInstall then
  begin
    AppPath := ExpandConstant('{app}');
    
    // 1. Create the local Windows .bat file
    BatContent := '@echo off' + #13#10 + 
                  'set PYTHONPATH=' + AppPath + '\Indra-cli' + #13#10 + 
                  'python "' + AppPath + '\Indra-cli\ckart\main.py" %*';
    SaveStringToFile(AppPath + '\Indra-cli\ckart.bat', BatContent, False);

    // 2. Windows CLI Installation
    if WinCliCheckBox.Checked then
    begin
      Exec('cmd.exe', '/c pip install -r "' + AppPath + '\Indra-cli\requirements.txt"', '', SW_HIDE, ewWaitUntilTerminated, Res);
      Exec('powershell.exe', '-ExecutionPolicy Bypass -File "' + AppPath + '\Indra-cli\Install-ckart.ps1"', '', SW_HIDE, ewWaitUntilTerminated, Res);
    end;

    // 3. WSL Setup
    if WslCheckBox.Checked then
    begin
      // Trigger WSL install (no-op if already present)
      Exec('wsl.exe', '--install -d Ubuntu', '', SW_SHOW, ewWaitUntilTerminated, Res);
      
      // Perform configuration as the user 'harshith'
      RunCkartInsideWsl();
      
      MsgBox('Installation complete! ComputeKart is configured for Windows and WSL.', mbInformation, MB_OK);
    end;
  end;
end;