; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "ComputeKart"
#define MyAppVersion "0.1.3"
#define MyAppPublisher "computekart.com"
#define MyAppURL "https://computekart.com/home"
#define MyAppExeName "compute_kart.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{16CEA89B-A740-4EA8-9B95-52081A792F59}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes

; CRITICAL: Admin privileges are explicitly required to install Windows Subsystem for Linux (WSL).
PrivilegesRequired=admin

OutputDir=D:\project-extra\new\compute_kart\installers
OutputBaseFilename=computekart
SetupIconFile=D:\project-extra\new\clientFrontend\public\favicon.ico
SolidCompression=yes
WizardStyle=modern dynamic windows11

; NOTE: SignTool is commented out below so the script compiles without errors.
; SignTool=custom_signtool $f

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\project-extra\new\compute_kart\build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\project-extra\new\compute_kart\build\windows\x64\runner\Release\dartjni.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\project-extra\new\compute_kart\build\windows\x64\runner\Release\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\project-extra\new\compute_kart\build\windows\x64\runner\Release\screen_retriever_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\project-extra\new\compute_kart\build\windows\x64\runner\Release\url_launcher_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\project-extra\new\compute_kart\build\windows\x64\runner\Release\window_manager_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\project-extra\new\compute_kart\build\windows\x64\runner\Release\flutter_pty.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\project-extra\new\compute_kart\build\windows\x64\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs

; --- VC++ Redistributable Installer ---
Source: "D:\project-extra\new\compute_kart\build\windows\x64\runner\Release\vc_redist.x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall

; --- Bundle entire Indra-cli folder for WSL Installation ---
Source: "D:\project-extra\new\Indra-cli\*"; DestDir: "{app}\Indra-cli"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; --- Silently run VC++ installer if missing ---
Filename: "{tmp}\vc_redist.x64.exe"; Parameters: "/quiet /norestart"; Check: VCUpdateRequired; Flags: waituntilterminated

; --- Run WSL installation if missing ---
; Using 'runhidden' so the command window doesn't look messy to users.
Filename: "wsl.exe"; Parameters: "--install --no-distribution"; Check: WSLInstallationRequired; Flags: runhidden waituntilterminated

; --- Run ckart CLI Installation inside WSL ---
Filename: "wsl.exe"; Parameters: "bash -c ""cd '$(wslpath '{app}\Indra-cli')' && sed -i 's/\r$//' Install-ckart.sh && chmod +x Install-ckart.sh && ./Install-ckart.sh"""; Flags: waituntilterminated

; --- App execution launcher ---
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
var
  WslInstalledDuringSetup: Boolean;

function VCUpdateRequired: Boolean;
var
  Version: String;
begin
  if RegQueryStringValue(HKLM64, 'SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64', 'Version', Version) then
  begin
    Result := False;
  end
  else
  begin
    Result := True;
  end;
end;

function WSLInstallationRequired: Boolean;
begin
  // Check if wsl.exe is available in the native System32 folder.
  if FileExists(ExpandConstant('{sys}\wsl.exe')) then
  begin
    Result := False;
  end
  else
  begin
    Result := True;
    // Track that we are triggering a WSL installation so we can request a reboot later.
    WslInstalledDuringSetup := True;
  end;
end;

// This built-in Inno Setup function tells the installer whether it needs to prompt for a restart at the end.
function NeedRestart: Boolean;
begin
  if WslInstalledDuringSetup then
    Result := True
  else
    Result := False;
end;