; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "ComputeKart"
#define MyAppVersion "0.1.3"
#define MyAppPublisher "computekart.com"
#define MyAppURL "https://computekart.com/home"
#define MyAppExeName "compute_kart.exe"

; Since the .iss file is in the "installers" folder, SourcePath is compute_kart/installers/.
; Adding "\.." backs out into the actual project root folder (desktop_computekart/).
#define MyAppRootDir SourcePath + "\.."

[Setup]
AppId={{16CEA89B-A740-4EA8-9B95-52081A792F59}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes

; Admin privileges are required to configure WSL features and system environment variables
PrivilegesRequired=admin
ChangesEnvironment=yes

OutputDir={#SourcePath}
OutputBaseFilename=computekart
SetupIconFile={#MyAppRootDir}\assets\favicon.ico
SolidCompression=yes
WizardStyle=modern dynamic windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#MyAppRootDir}\build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppRootDir}\build\windows\x64\runner\Release\*.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppRootDir}\build\windows\x64\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#MyAppRootDir}\assets\VC_redist.x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "{#MyAppRootDir}\Indra-cli\*"; DestDir: "{app}\Indra-cli"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Registry]
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; \
    ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}\Indra-cli"; \
    Check: NeedsAddPath(ExpandConstant('{app}\Indra-cli'))

[Run]
; Core framework requirements run at the end of standard installation
Filename: "{tmp}\VC_redist.x64.exe"; Parameters: "/quiet /norestart"; Check: VCUpdateRequired; Flags: waituntilterminated

[Code]
var
  WslCustomPage: TWizardPage;
  WslCheckBox: TNewCheckBox;
  CliCheckBox: TNewCheckBox;
  WslInstalledDuringSetup: Boolean;

function VCUpdateRequired: Boolean;
var Version: String;
begin
  Result := not RegQueryStringValue(HKLM64, 'SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64', 'Version', Version);
end;

function NeedsAddPath(Param: string): boolean;
var OrigPath: string;
begin
  if not RegQueryStringValue(HKLM, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'Path', OrigPath) then
  begin
    Result := True;
    exit;
  end;
  Result := Pos(';' + UpperCase(Param) + ';', ';' + UpperCase(OrigPath) + ';') = 0;
end;

// Checks if the wsl execution binary is registered natively
function IsWslInstalled: Boolean;
begin
  Result := FileExists(ExpandConstant('{sys}\wsl.exe'));
end;

// --- STEP 1: Creating the Custom UI Selection Page ---
procedure InitializeWizard;
begin
  WslCustomPage := CreateCustomPage(wpReady, 'Environment Components Setup', 'Select the backend tools you want to install.');

  // Add the WSL Configuration Checkbox
  WslCheckBox := TNewCheckBox.Create(WslCustomPage);
  WslCheckBox.Parent := WslCustomPage.Surface;
  WslCheckBox.Top := 10;
  WslCheckBox.Width := WslCustomPage.SurfaceWidth;
  WslCheckBox.Caption := 'Install Windows Subsystem for Linux (WSL) & Ubuntu Distribution';
  WslCheckBox.Checked := not IsWslInstalled;

  // Add the ckart CLI Checkbox
  CliCheckBox := TNewCheckBox.Create(WslCustomPage);
  CliCheckBox.Parent := WslCustomPage.Surface;
  CliCheckBox.Top := WslCheckBox.Top + 30;
  CliCheckBox.Width := WslCustomPage.SurfaceWidth;
  CliCheckBox.Caption := 'Install and register ckart CLI inside Linux Environment';
  CliCheckBox.Checked := True;
end;

// --- STEP 2: Handle Background Execution After Files Copy Successfully ---
procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
begin
  // This executes right after files are copied, which safely preserves the restart flag context
  if CurStep = ssPostInstall then
  begin
    // Part A: Execute WSL Installation if checked
    if WslCheckBox.Checked then
    begin
      if not IsWslInstalled then
      begin
        // Install core WSL engine
        Exec('wsl.exe', '--install --no-distribution', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
        WslInstalledDuringSetup := True;
      end;

      // Part B: Download and configure distribution packages
      Exec('wsl.exe', '--install -d Ubuntu', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    end;

    // Part C: Execute ckart CLI Configuration inside Linux
    if CliCheckBox.Checked then
    begin
      // If a system reboot is hard-required, we skip running the script now to prevent a freeze/crash.
      if not WslInstalledDuringSetup then
      begin
        // Run your installation shell script within the live environment instance
        Exec('wsl.exe', 'bash -c "cd ''' + '$(wslpath ''' + ExpandConstant('{app}\Indra-cli') + ''')''' + ' && sed -i ' + '''s/\r$//''' + ' Install-ckart.sh && chmod +x Install-ckart.sh && ./Install-ckart.sh"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
      end;
    end;
  end;
end;

// --- STEP 3: Handle Automatic Reboot Request ---
function NeedRestart: Boolean;
begin
  Result := WslInstalledDuringSetup;
end;